import sys
import os
import trimesh
import skeletor as sk
import navis
import numpy as np
import time
import open3d as o3d
from scipy.spatial import cKDTree
import collections

print("--- 載入修正版 v4 (Manual SWC Writer) ---") 

def load_mesh(in_path):
    if not os.path.exists(in_path):
        print(f"Error: Input file not found {in_path}")
        return None
    try:
        mesh = trimesh.load(in_path)
        if isinstance(mesh, trimesh.Scene):
            mesh = trimesh.util.concatenate(mesh.dump(concatenate=True))
        return mesh
    except Exception as e:
        print(f"載入錯誤: {e}")
        return None

def simplify_mesh_with_open3d(trimesh_mesh, target_faces):
    """ 使用 Open3D 進行網格簡化 (QEM) """
    try:
        o3d_mesh = o3d.geometry.TriangleMesh()
        o3d_mesh.vertices = o3d.utility.Vector3dVector(trimesh_mesh.vertices)
        o3d_mesh.triangles = o3d.utility.Vector3iVector(trimesh_mesh.faces)
        
        print(f"   [Open3D] 正在將 {len(o3d_mesh.triangles)} 面簡化至 {target_faces} 面...")
        simplified_o3d = o3d_mesh.simplify_quadric_decimation(target_number_of_triangles=target_faces)
        
        new_vertices = np.asarray(simplified_o3d.vertices)
        new_faces = np.asarray(simplified_o3d.triangles)
        
        if len(new_faces) == 0:
            print("   [Warning] 簡化後網格為空，將使用原始網格。")
            return trimesh_mesh

        return trimesh.Trimesh(vertices=new_vertices, faces=new_faces)
    except Exception as e:
        print(f"   [Open3D] 簡化過程發生錯誤: {e}")
        return trimesh_mesh 

def save_swc_manual(skeleton, filepath):
    """
    手動將骨架數據寫入 SWC 檔案，繞過 navis 的錯誤。
    SWC 格式: id type x y z radius parent_id
    """
    print("   [Manual] 正在手動構建 SWC 結構...")
    
    # 1. 獲取頂點 (Vertices)
    if hasattr(skeleton, 'vertices'):
        vertices = skeleton.vertices
    elif hasattr(skeleton, 'nodes'):
        vertices = skeleton.nodes[['x', 'y', 'z']].values
    else:
        raise ValueError("無法找到骨架頂點數據")

    # 2. 獲取邊 (Edges)
    edges = []
    if hasattr(skeleton, 'edges'):
        edges = skeleton.edges
    elif hasattr(skeleton, 'connectivity'):
        edges = skeleton.connectivity
    
    num_nodes = len(vertices)
    
    # 3. 構建鄰接表 (Adjacency List)
    adj = collections.defaultdict(list)
    if len(edges) > 0:
        for u, v in edges:
            adj[u].append(v)
            adj[v].append(u)
    else:
        print("   [Warning] 骨架中沒有發現連接邊 (Edges)，將儲存為離散點。")

    # 4. BFS 遍歷以建立父子關係 (SWC 需要樹狀結構)
    # parent_map: 儲存每個節點的父節點 ID，-1 代表根
    parent_map = np.full(num_nodes, -1, dtype=int)
    visited = np.zeros(num_nodes, dtype=bool)
    
    # 處理可能斷開的多個骨架部分
    for start_node in range(num_nodes):
        if not visited[start_node]:
            # 對每個未訪問的連通分量進行 BFS
            queue = collections.deque([start_node])
            visited[start_node] = True
            # 根節點的 parent 保持 -1
            
            while queue:
                u = queue.popleft()
                for v in adj[u]:
                    if not visited[v]:
                        visited[v] = True
                        parent_map[v] = u + 1 # SWC ID 通常從 1 開始，這裡存的是父節點的 ID
                        queue.append(v)

    # 5. 寫入檔案
    try:
        with open(filepath, 'w') as f:
            f.write("# SWC output generated by Manual Writer\n")
            f.write("# id type x y z radius parent_id\n")
            for i in range(num_nodes):
                node_id = i + 1
                pid = parent_map[i] # 這裡已经是 ID 格式 (或者 -1)
                x, y, z = vertices[i]
                radius = 1.0 # 預設半徑
                # type 0 = undefined
                f.write(f"{node_id} 0 {x:.4f} {y:.4f} {z:.4f} {radius:.2f} {pid}\n")
        print(f"   -> [Success] 手動 SWC 寫入成功: {filepath}")
        return True
    except Exception as e:
        print(f"   [Error] 手動寫入失敗: {e}")
        return False

def skeletonize_mesh(in_path, out_folder, contrast_factor=1.0, auto_simplify=True):
    start_time = time.time()
    print(f"--- 開始處理: {os.path.basename(in_path)} ---")

    # 1. Load
    mesh = load_mesh(in_path)
    if mesh is None: return

    print(f"原始網格: {len(mesh.vertices)} 頂點, {len(mesh.faces)} 面")

    # --- 自動簡化 ---
    if auto_simplify:
        target_faces = 20000 
        if len(mesh.faces) > target_faces:
            print(f"⚡ [自動簡化開啟] 網格過大，正在呼叫 Open3D 簡化...")
            mesh = simplify_mesh_with_open3d(mesh, target_faces)
            print(f"   -> 簡化後: {len(mesh.vertices)} 頂點, {len(mesh.faces)} 面")
        else:
            print("ℹ️ 網格面數適中，不需簡化。")
    else:
        print("🔒 [自動簡化關閉] 使用原始網格...")

    # 2. Pre-processing
    print("正在修復網格 (Fixing)...")
    fixed_mesh = sk.pre.fix_mesh(mesh, remove_disconnected=5, inplace=False)

    try:
        # 3. Contraction
        print(f"正在收縮網格 (epsilon={contrast_factor})...")
        contracted_mesh = sk.pre.contract(fixed_mesh, epsilon=contrast_factor)
        
        # 4. Skeletonize
        print(f"正在轉換為骨架...")
        skeleton = sk.skeletonize.by_vertex_clusters(contracted_mesh, sampling_dist=contrast_factor)

        # 檢查骨架是否有內容
        has_verts = hasattr(skeleton, 'vertices') and len(skeleton.vertices) > 0
        has_nodes = hasattr(skeleton, 'nodes') and len(skeleton.nodes) > 0
        
        if not (has_verts or has_nodes):
            print("❌ 錯誤: 生成骨架為空。")
            return

        # 5. Post-processing
        print(f"正在清理雜枝...")
        threshold = fixed_mesh.bounding_box.extents.max() * 0.05
        clean_skeleton = sk.post.clean_up(skeleton, prune=threshold)
            
        # 6. Export
        os.makedirs(out_folder, exist_ok=True)
        skel_file_swc = os.path.join(out_folder, 'skeleton.swc')
        
        # 獲取節點數供顯示
        node_count = len(clean_skeleton.vertices) if hasattr(clean_skeleton, 'vertices') else len(clean_skeleton.nodes)
        print(f"正在寫入 SWC 檔案 ({node_count} nodes)...")
        
        # --- 最終儲存策略 ---
        # 優先嘗試手動寫入 (最穩定)
        if not save_swc_manual(clean_skeleton, skel_file_swc):
            # 如果手動失敗，嘗試 Navis
            print("   [Info] 轉用 Navis 寫入...")
            try:
                navis.write_swc(clean_skeleton, skel_file_swc)
            except Exception as e:
                print(f"   [Error] 所有 SWC 寫入方式皆失敗。儲存點雲備份。")
                xyz_file = os.path.join(out_folder, 'skeleton_points.xyz')
                pts = clean_skeleton.vertices if hasattr(clean_skeleton, 'vertices') else clean_skeleton.nodes[['x','y','z']].values
                np.savetxt(xyz_file, pts)

        elapsed = time.time() - start_time
        print(f"✅ 處理完成！耗時: {elapsed:.2f} 秒")
        
    except Exception as e:
        print(f"\n執行錯誤: {e}")
        import traceback
        traceback.print_exc()

def main():
    if len(sys.argv) < 3:
        print("Usage: python transform_meshcskeletor.py <in_path> <out_folder> [contrast_factor] [auto_simplify(0/1)]")
        sys.exit(1)

    in_path = sys.argv[1]
    out_folder = sys.argv[2]
    contrast_factor = 1.0
    auto_simplify = True

    if len(sys.argv) > 3:
        contrast_factor = float(sys.argv[3])
    
    if len(sys.argv) > 4:
        val = sys.argv[4]
        auto_simplify = val.lower() in ['true', '1', 'yes', 'y']

    skeletonize_mesh(in_path, out_folder, contrast_factor, auto_simplify)

if __name__ == "__main__":
    main()